INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (137, 'AF', 'AFR', 'Air France', 1);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (2660, 'HU', 'CHH', 'Hainan Airlines', 1);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (2987, 'JL', 'JAL', 'Japan Airlines', 1);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (3163, 'KE', 'KAL', 'Korean Air', 1);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (4091, 'QR', 'QTR', 'Qatar Airways', 1);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (4296, 'FR', 'RYR', 'Ryanair', 1);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (4435, 'SQ', 'SIA', 'Singapore Airlines', 1);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (4951, 'TK', 'THY', 'Turkish Airlines', 1);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (5347, 'VS', 'VIR', 'Virgin Atlantic Airways', 1);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (19, null, 'BZS', 'Aero Biniza', 0);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (416, null, 'SUN', 'Antillana De Navegacion Aerea', 0);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (558, null, 'AWO', 'Awood Air Ltd.', 0);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (619, null, 'NFF', 'Aircraft Support and Services', 0);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (1074, null, 'MLF', 'Amal Airlines', 0);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (1754, null, 'CAD', 'Chilliwack Aviation', 0);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (1786, null, 'FIV', 'Citationshares', 0);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (1939, null, 'RGN', 'Cygnus Air', 0);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (2183, 'EK', 'UAE', 'Emirates', 1);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (2593, null, 'GOM', 'Gomel Airlines', 0);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (3463, 'IG', 'ISS', 'Meridiana', 1);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (3472, null, 'MEX', 'Metro Express', 0);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (3913, null, 'PSC', 'Pascan Aviation', 0);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (4168, null, 'RGY', 'Regency Airlines', 0);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (4290, null, 'RUA', 'Rwanda Airlines', 0);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (4676, '1I', null, 'Sierra Nevada Airlines', 0);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (5085, 'UG', 'TUI', 'Tuninter', 1);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (5100, null, 'TWJ', 'Twinjet Aircraft Sales', 0);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (17023, 'Y5', 'AWA', 'Asia Wings', 1);
INSERT INTO Airline (AirlineID, IataCode, IcaoCode, Name, Active) VALUES (20802, 'GX', 'GXG', 'GermanXL', 1);