INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (7, 'UAK', 'BGBW', 'Narsarsuaq Airport', 'Narssarssuaq', 'Greenland', '-3', 'E');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (84, 'YLJ', 'CYLJ', 'Meadow Lake Airport', 'Meadow Lake', 'Canada', '-6', 'N');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (238, 'HME', 'DAUH', 'Oued Irara Airport', 'Hassi Messaoud', 'Algeria', '1', 'N');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (495, 'SOU', 'EGHI', 'Southampton Airport', 'Southampton', 'United Kingdom', '0', 'E');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (503, 'LCY', 'EGLC', 'London City Airport', 'London', 'United Kingdom', '0', 'E');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (506, 'BBS', 'EGLK', 'Blackbushe Airport', 'Blackbushe', 'United Kingdom', '0', 'E');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (612, 'KRP', 'EKKA', 'Karup Airport', 'Karup', 'Denmark', '1', 'E');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (929, 'MJN', 'FMNM', 'Amborovy Airport', 'Mahajanga', 'Madagascar', '3', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (1029, 'KLI', 'FZFP', 'Kotakoli Airport', 'Kotakoli', 'Congo (Kinshasa)', '1', 'N');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (1140, 'KIS', 'HKKI', 'Kisumu Airport', 'Kisumu', 'Kenya', '3', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (1177, 'DAR', 'HTDA', 'Julius Nyerere International Airport', 'Dar Es Salaam', 'Tanzania', '3', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (1276, 'LDE', 'LFBT', 'Tarbes-Lourdes-Pyrénées Airport', 'Tarbes', 'France', '1', 'E');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (1775, 'TEA', 'MHTE', 'Tela Airport', 'Tela', 'Honduras', '-6', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (1793, 'CTM', 'MMCM', 'Chetumal International Airport', 'Chetumal', 'Mexico', '-5', 'S');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (1975, 'TIH', 'NTGC', 'Tikehau Airport', 'Tikehau', 'French Polynesia', '-10', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (2081, 'RAH', 'OERF', 'Rafha Domestic Airport', 'Rafha', 'Saudi Arabia', '3', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (2297, 'TSJ', 'RJDT', 'Tsushima Airport', 'Tsushima', 'Japan', '9', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (2311, 'KKJ', 'RJFR', 'Kitakyūshū Airport', 'Kitakyushu', 'Japan', '9', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (2537, 'CNF', 'SBCF', 'Tancredo Neves International Airport', 'Belo Horizonte', 'Brazil', '-3', 'S');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (2681, 'MCH', 'SEMH', 'General Manuel Serrano Airport', 'Machala', 'Ecuador', '-5', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (2802, 'AQP', 'SPQU', 'Rodríguez Ballón International Airport', 'Arequipa', 'Peru', '-5', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (2922, 'GYD', 'UBBB', 'Heydar Aliyev International Airport', 'Baku', 'Azerbaijan', '4', 'E');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (2948, 'LED', 'ULLI', 'Pulkovo Airport', 'St. Petersburg', 'Russia', '3', 'N');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (2968, 'CEK', 'USCC', 'Chelyabinsk Balandino Airport', 'Chelyabinsk', 'Russia', '5', 'N');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (2990, 'KZN', 'UWKD', 'Kazan International Airport', 'Kazan', 'Russia', '3', 'N');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (3002, 'BHO', 'VABP', 'Raja Bhoj International Airport', 'Bhopal', 'India', '5.5', 'N');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (3261, 'SOQ', 'WAXX', 'Dominique Edward Osok Airport', 'Sorong', 'Indonesia', '9', 'N');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (3324, 'ISA', 'YBMA', 'Mount Isa Airport', 'Mount Isa', 'Australia', '10', 'O');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (3339, 'MEL', 'YMML', 'Melbourne International Airport', 'Melbourne', 'Australia', '10', 'O');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (3341, 'ADL', 'YPAD', 'Adelaide International Airport', 'Adelaide', 'Australia', '9.5', 'O');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (3361, 'SYD', 'YSSY', 'Sydney Kingsford Smith International Airport', 'Sydney', 'Australia', '10', 'O');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (3363, 'WGA', 'YSWG', 'Wagga Wagga City Airport', 'Wagga Wagga', 'Australia', '10', 'O');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (3446, 'PRC', 'KPRC', 'Ernest A. Love Field', 'Prescott', 'United States', '-7', 'A');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (3462, 'PHX', 'KPHX', 'Phoenix Sky Harbor International Airport', 'Phoenix', 'United States', '-7', 'N');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (3484, 'LAX', 'KLAX', 'Los Angeles International Airport', 'Los Angeles', 'United States', '-8', 'A');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (3743, 'FMN', 'KFMN', 'Four Corners Regional Airport', 'Farmington', 'United States', '-7', 'A');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (3751, 'DEN', 'KDEN', 'Denver International Airport', 'Denver', 'United States', '-7', 'A');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (3767, 'IAB', 'KIAB', 'Mc Connell Air Force Base', 'Wichita', 'United States', '-6', 'A');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (3804, 'CYS', 'KCYS', 'Cheyenne Regional Jerry Olson Field', 'Cheyenne', 'United States', '-7', 'A');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (3892, 'TSY', 'WICM', 'Cibeureum Airport', 'Tasikmalaya', 'Indonesia', '7', 'N');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (3975, 'TAI', 'OYTZ', 'Ta''izz International Airport', 'Taiz', 'Yemen', '3', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (4020, 'BZN', 'KBZN', 'Gallatin Field', 'Bozeman', 'United States', '-7', 'A');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (4029, 'DME', 'UUDD', 'Domodedovo International Airport', 'Moscow', 'Russia', '3', 'N');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (4062, 'ARM', 'YARM', 'Armidale Airport', 'Armidale', 'Australia', '10', 'O');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (4078, 'OVB', 'UNNT', 'Tolmachevo Airport', 'Novosibirsk', 'Russia', '7', 'N');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (4194, 'JNX', 'LGNX', 'Naxos Airport', 'Cyclades Islands', 'Greece', '2', 'E');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (4341, 'LBL', 'KLBL', 'Liberal Mid-America Regional Airport', 'Liberal', 'United States', '-6', 'A');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (5432, 'MIS', 'AYMS', 'Misima Island Airport', 'Misima Island', 'Papua New Guinea', '10', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (5568, 'SOY', 'EGER', 'Stronsay Airport', 'Stronsay', 'United Kingdom', '0', 'E');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (5880, 'HPA', 'NFTL', 'Lifuka Island Airport', 'Lifuka', 'Tonga', '13', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (5991, 'LZN', 'RCFG', 'Matsu Nangan Airport', 'Matsu Islands', 'Taiwan', '8', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (6075, 'DSD', 'TFFA', 'La Désirade Airport', 'Grande Anse', 'Guadeloupe', '-4', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (6217, 'MKM', 'WBGK', 'Mukah Airport', 'Mukah', 'Malaysia', '8', 'N');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (6249, 'BHS', 'YBTH', 'Bathurst Airport', 'Bathurst', 'Australia', '10', 'O');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (6276, 'JCK', 'YJLC', 'Julia Creek Airport', 'Julia Creek', 'Australia', '10', 'O');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (6294, 'MIM', 'YMER', 'Merimbula Airport', 'Merimbula', 'Australia', '10', 'O');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (6317, 'PKE', 'YPKS', 'Parkes Airport', 'Parkes', 'Australia', '10', 'O');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (6334, 'WYA', 'YWHA', 'Whyalla Airport', 'Whyalla', 'Australia', '9.5', 'O');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (6338, 'BWT', 'YWYY', 'Wynyard Airport', 'Burnie', 'Australia', '10', 'O');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (6342, 'CIF', 'ZBCF', 'Chifeng Airport', 'Chifeng', 'China', '8', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (6754, 'AFS', 'UTSN', 'Sugraly Airport', 'Zarafshan', 'Uzbekistan', '5', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (6969, 'NBC', 'UWKE', 'Begishevo Airport', 'Nizhnekamsk', 'Russia', '3', 'N');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (7078, 'SOW', 'KSOW', 'Show Low Regional Airport', 'Show Low', 'United States', '-7', 'A');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (7181, 'ORV', 'PFNO', 'Robert (Bob) Curtis Memorial Airport', 'Noorvik', 'United States', '-9', 'A');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (7205, 'KLW', 'PAKW', 'Klawock Airport', 'Klawock', 'United States', '-9', 'A');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (7264, 'YCR', 'CYCR', 'Cross Lake (Charlie Sinclair Memorial) Airport', 'Cross Lake', 'Canada', '-6', 'A');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (7546, 'PGU', 'OIBP', 'Persian Gulf International Airport', 'Khalije Fars', 'Iran', '3.5', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (7619, 'XYA', 'AGGY', 'Yandina Airport', 'Yandina', 'Solomon Islands', '11', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (7857, 'BCE', 'KBCE', 'Bryce Canyon Airport', 'Bryce Canyon', 'United States', '-7', 'A');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (7906, 'NYW', 'VYMY', 'Monywar Airport', 'Monywa', 'Burma', '6.5', 'N');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (7976, 'UKA', 'HKUK', 'Ukunda Airstrip', 'Ukunda', 'Kenya', '3', 'U');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (7999, 'HSH', 'KHND', 'Henderson Executive Airport', 'Henderson', 'United States', '-8', 'A');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (9904, 'RCM', 'YRMD', 'Richmond Airport', 'Richmond', 'Australia', '10', 'N');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (10069, 'KRQ', 'UKCK', 'Kramatorsk Airport', 'Kramatorsk', 'Ukraine', '2', 'E');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (10137, 'DU9', 'CDU9', 'Dunnville Airport', 'Dunnville', 'Canada', '-5', 'A');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (10185, 'PRB', 'KPRB', 'Paso Robles Municipal Airport', 'Paso Robles', 'United States', '-8', 'A');
INSERT INTO Airport (AirportID, IataCode, IcaoCode, Name, City, Country, Timezone, Dst) VALUES (13478, 'CDE', 'ZBCD', 'Chengde Puning Airport', 'Chengde', 'China', '8', 'N');
