INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (1, 'Ruth', 'Griffiths', 'Pilot', 6342);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (2, 'Henry', 'Smith', 'Ground Staff', 7976);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (3, 'Bradley', 'Newman', 'Pilot', 10069);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (4, 'Sian', 'Cox', 'Pilot', 2681);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (5, 'Janice', 'Hopkins', 'Pilot', 495);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (6, 'Mary', 'Higgins', 'Ground Staff', 6075);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (7, 'Colin', 'Lloyd', 'Cabin Crew', 3261);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (8, 'Leanne', 'Foster', 'Pilot', 7906);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (9, 'Chelsea', 'Ryan', 'Pilot', 6217);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (10, 'Francesca', 'Harrison', 'Cabin Crew', 6754);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (11, 'Samantha', 'Quinn', 'Pilot', 7619);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (12, 'Joan', 'White', 'Cabin Crew', 503);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (13, 'Thomas', 'Reed', 'Cabin Crew', 506);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (14, 'Sam', 'Harrison', 'Pilot', 5991);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (15, 'Maurice', 'White', 'Cabin Crew', 3002);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (16, 'Robin', 'Andrews', 'Cabin Crew', 7181);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (17, 'Tom', 'Warner', 'Pilot', 5432);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (18, 'Jessica', 'Glover', 'Cabin Crew', 612);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (19, 'Leigh', 'Butler', 'Dispatcher', 10137);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (20, 'Samuel', 'Elliott', 'Cabin Crew', 3751);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (21, 'Paula', 'Harvey', 'Ground Staff', 929);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (22, 'Gemma', 'Ferguson', 'Dispatcher', 3975);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (23, 'Billy', 'Norton', 'Cabin Crew', 3767);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (24, 'Marian', 'Young', 'Pilot', 5568);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (25, 'Linda', 'Mellor', 'Ground Staff', 2311);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (26, 'Geraldine', 'Rees', 'Cabin Crew', 13478);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (27, 'Irene', 'Wilson', 'Cabin Crew', 4194);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (28, 'Gregory', 'Robinson', 'Cabin Crew', 10185);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (29, 'Donald', 'Taylor', 'Cabin Crew', 2297);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (30, 'Jessica', 'White', 'Pilot', 2081);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (31, 'Heather', 'Lee', 'Dispatcher', 7);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (32, 'Ben', 'Middleton', 'Pilot', 3892);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (33, 'Rhys', 'Davies', 'Pilot', 4020);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (34, 'Rita', 'Cross', 'Cabin Crew', 7264);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (35, 'Eileen', 'Hammond', 'Pilot', 238);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (36, 'Heather', 'Thompson', 'Cabin Crew', 2802);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (37, 'Duncan', 'Humphries', 'Pilot', 1793);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (38, 'Jessica', 'Dixon', 'Pilot', 1029);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (39, 'Ruth', 'Holmes', 'Pilot', 1140);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (40, 'Gerald', 'Richardson', 'Cabin Crew', 1177);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (41, 'William', 'Wilson', 'Pilot', 84);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (42, 'Ryan', 'Nelson', 'Cabin Crew', 1276);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (43, 'Joanne', 'Phillips', 'Pilot', 7999);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (44, 'Phillip', 'Johnston', 'Pilot', 5880);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (45, 'Kirsty', 'Hawkins', 'Cabin Crew', 7546);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (46, 'Guy', 'Kelly', 'Cabin Crew', 7857);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (47, 'Dawn', 'Byrne', 'Cabin Crew', 1975);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (48, 'Carly', 'Hale', 'Pilot', 2537);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (49, 'Arthur', 'Davidson', 'Pilot', 1775);
INSERT INTO Staff (StaffID, FirstName, LastName, Role, BaseAirportID) VALUES (50, 'Chelsea', 'Powell', 'Pilot', 7205);
