INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (1, 24, 42, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (4, 17, 11, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (7, 7, 26, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (8, 24, 1, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (9, 18, 3, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (10, 9, 40, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (11, 1, 40, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (14, 32, 48, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (16, 6, 2, 'Standby');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (17, 15, 29, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (19, 20, 10, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (21, 11, 41, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (22, 11, 37, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (24, 30, 14, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (27, 5, 24, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (29, 26, 22, 'Standby');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (31, 21, 7, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (32, 15, 31, 'Ops');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (33, 18, 16, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (34, 34, 23, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (37, 7, 27, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (38, 32, 33, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (39, 30, 17, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (42, 34, 38, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (43, 4, 41, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (46, 11, 1, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (47, 6, 5, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (52, 5, 35, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (54, 20, 46, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (56, 22, 45, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (57, 30, 31, 'Ops');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (59, 3, 38, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (61, 32, 6, 'Standby');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (62, 7, 36, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (63, 34, 2, 'Ops');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (64, 27, 15, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (66, 26, 27, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (67, 21, 40, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (68, 5, 49, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (69, 15, 34, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (70, 7, 50, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (71, 2, 3, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (73, 34, 49, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (74, 11, 44, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (76, 15, 23, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (77, 17, 36, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (79, 20, 34, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (80, 30, 18, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (83, 26, 43, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (84, 32, 26, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (86, 9, 10, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (88, 6, 19, 'Standby');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (91, 17, 21, 'Standby');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (92, 22, 36, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (94, 24, 33, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (96, 17, 28, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (97, 15, 47, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (98, 15, 36, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (99, 27, 3, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (100, 20, 2, 'Ops');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (102, 30, 50, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (104, 27, 19, 'Ops');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (105, 24, 37, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (106, 24, 49, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (108, 4, 11, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (109, 30, 11, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (110, 4, 20, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (114, 18, 15, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (116, 2, 32, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (117, 21, 17, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (118, 9, 42, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (119, 5, 28, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (121, 34, 48, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (122, 4, 31, 'Standby');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (124, 5, 27, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (125, 5, 44, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (127, 30, 34, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (130, 22, 29, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (131, 7, 30, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (132, 24, 25, 'Standby');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (133, 5, 4, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (135, 4, 45, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (137, 4, 22, 'Standby');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (141, 18, 34, 'Purser');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (142, 18, 17, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (143, 22, 9, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (144, 26, 48, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (145, 6, 18, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (146, 27, 16, 'Cabin Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (147, 20, 3, 'Crew');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (148, 4, 44, 'Captain');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (149, 6, 49, 'First Officer');
INSERT INTO CrewAssignment (CrewAssignmentID, InstanceID, StaffID, DutyRole) VALUES (150, 32, 34, 'Cabin Crew');
