INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (1, 18, 7, 'MOIJESG68', 'ARE', '21B', 'First', 'Confirmed');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (2, 20, 27, 'PJS1AWP0L', 'USA', '16B', 'Business', 'Cancelled');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (3, 16, 2, 'SEF6Y39C2', 'AUS', '6D', 'First', 'Cancelled');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (4, 5, 17, '9YSQJVFJW', 'FRA', '24D', 'Business', 'Confirmed');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (5, 15, 18, 'MOIJESG68', 'ARE', '40F', 'Economy', 'Confirmed');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (6, 13, 24, 'BUK3XF1GP', 'ESP', '22E', 'Business', 'CheckedIn');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (7, 23, 22, 'Z7FZTVOVK', 'USA', '31E', 'First', 'Confirmed');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (8, 17, 9, '7XE78669B', 'ESP', '21E', 'Business', 'Confirmed');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (9, 24, 20, '4MX23SY67', 'ESP', '38C', 'First', 'CheckedIn');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (10, 16, 2, 'SEF6Y39C2', 'AUS', '24C', 'Economy', 'Cancelled');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (11, 10, 2, '0XP2S2O8P', 'FRA', '39D', 'Business', 'Cancelled');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (12, 25, 15, 'NJ971HSPT', 'USA', '4E', 'First', 'Confirmed');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (13, 24, 4, 'YFXOBUGVJ', 'IND', '9E', 'Premium Economy', 'Confirmed');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (14, 16, 34, 'HSFKR26J1', 'USA', '25C', 'Premium Economy', 'Confirmed');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (15, 8, 18, 'JQMLJEL53', 'AUS', '36C', 'Premium Economy', 'Cancelled');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (16, 18, 18, '6LCP2277K', 'DEU', '19A', 'First', 'Boarded');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (17, 18, 18, 'DP03EH58B', 'ARE', '36F', 'Business', 'Confirmed');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (18, 4, 27, 'Y8O69WEZC', 'ESP', '22F', 'First', 'Confirmed');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (19, 5, 1, 'CS4I42AFB', 'FRA', '36B', 'First', 'CheckedIn');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (20, 2, 6, 'KMIQD4X9G', 'ARE', '42E', 'Premium Economy', 'Confirmed');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (21, 4, 22, '4MX23SY67', 'ESP', '19D', 'First', 'Boarded');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (22, 17, 30, 'Z7FZTVOVK', 'USA', '18B', 'Economy', 'Confirmed');
INSERT INTO BookingItem (BookingItemID, BookingID, InstanceID, PassportNo, Nationality, SeatNo, CabinClass, ItemStatus) VALUES (23, 15, 17, 'YFXOBUGVJ', 'IND', '12A', 'Business', 'CheckedIn');
